
CREATE TABLE minions (
    id INT PRIMARY KEY AUTO_INCREMENT ,
    name VARCHAR (40) NOT NULL ,
    age INT

);

CREATE TABLE towns (
    id INT PRIMARY KEY AUTO_INCREMENT ,
    name VARCHAR (40) NOT NULL
)

